### ISSUE TITLE
Running xprocess in a Docker container causes pytest to hang?

### ISSUE THREAD

**Issue by cquick01** [pytest-dev/pytest-xprocess#47] opened 2020-10-05 15:01 UTC
**Describe the bug**
Running a TCP server with `pytest-xprocess` works fine in my local Ubuntu environment, but when running in Docker, `pytest` seems to hang without completing any of the tests.

**To Reproduce**

Using the following fixture in my pytest script

```python
@pytest.fixture(scope = "session", autouse = True)
def host_sim_server(xprocess):
    python_executable_full_path = sys.executable

    class Starter(ProcessStarter):
        pattern = "HostSim server running"
        args = [python_executable_full_path, '-m', 'my_package.server_simulator']

    logfile = xprocess.ensure("host_sim", Starter)  # noqa: F841
    yield
    xprocess.getinfo("host_sim").terminate()
```

and `my_package.server_simulator` contains is a simple TCP server, with additional functions needed for testing added in the `Handler` class (essentially just functions to parse request packets, and respond, nothing that I think would effect pytest):

```python
 class HostSim:
     def __init__(self):
         HOST = "127.0.0.1"
         PORT = 1234
         socketserver.TCPServer.allow_reuse_address = True
         self.tcp_server = socketserver.TCPServer((HOST, PORT), Handler)

         logger.info("HostSim server running")
         self.tcp_server.serve_forever()

     def __del__(self):
         self.tcp_server.server_close()

if __name__ == "__main__":
    sim = HostSim()
```

**Expected behavior**
I'd expect the server to start, allowing all the other tests to complete successfully by connecting to `localhost:1234` (ie: where the server is listening) and performing the tests.

Log of running in my VM, succeeding:

```bash
$ PYTHONPATH=. pytest --cov=my_package tests/
====================================================================== test session starts =======================================================================
platform linux -- Python 3.8.5, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
rootdir: /home/cquick/cquick/my_package
plugins: cov-2.10.1, xprocess-0.14.0
collected 22 items

tests/a_test.py ..                                                                                                                                       [  9%]
tests/b_test.py ...                                                                                                                                     [ 22%]
tests/server_test.py .............                                                                                                                             [ 81%]
tests/c_test.py ....                                                                                                                                     [100%]

... [redacted, coverage report]

======================================================================= 22 passed in 3.17s =======================================================================
```

**Logs**

Log of running in Docker, and having it hang

```bash
$ docker run -it --rm --entrypoint "/bin/bash" -v "$PWD:/opt" my_pytest_image:xprocess
root@22fff798fc3b:/# cd opt/
root@22fff798fc3b:/opt# PYTHONPATH=. pytest --cov my_package tests/
====================================================================== test session starts =======================================================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /opt
plugins: xprocess-0.15.0, cov-2.10.0
collected 22 items

tests/a_test.py ..                                                                                                                                       [  9%]
tests/b_test.py ...                                                                                                                                     [ 22%]
tests/server_test.py
```

Here it just hangs

**Environment:**
 - OS: `Ubuntu 20.04.1 LTS`
 - Python Version: `3.8.5`
 - pytest-xprocess version: `0.14.0` and `0.15.0`
 - Docker Version: `19.03.13, build 4484c46d9d`
 - Docker Container Base Image: `python:3-buster`

Also, our `Dockerfile` is simply

```Dockerfile
FROM python:3-buster

RUN apt-get update && \
    apt-get -y full-upgrade && \
    apt-get -y install python3-pip

RUN pip install pytest pytest-cov pytest-xprocess
```

**Additional context**
In the Docker container, I am able to manually background the process and everything works, so I am fairly certain that Docker supports the multiprocessing/multithreading stuff.

```bash
$ python -m my_project.host_sim &
$ proc_id=$!
$ PYTHONPATH=. pytest --cov my_project tests/
$ kill $proc_id
```

_____

My main reason for using the `xprocess` package is to incorporate the server simulator in our CI testing, which uses Docker to run the CI jobs. As a work around, having the CI script be what I added in "Additional Context" does allow the tests to complete, but if course that isn't using `xprocess`. It seems much cleaner to be able to start the server from within pytest, which we'd like to get working.

I can provide additional information if requested.

Thanks you!

**Comment by northernSage** [comment] 2020-10-05 16:25
Hey there @cquick01. My first impression is that `xprocess` may be failing to match your server start pattern `"HostSim server running"` when within docker, or connections to `localhost:1234` are being refused/failing (can't really tell without seeing the contents of `tests/server_test.py`). Since, as you stated, everything is working fine outside docker, there's no point in me running this on my local machine since it would probably work as well. The fastest way to solve the issue would be if you could provide a minimal docker solution so I could get the containers running and debug.

**Comment by cquick01** [comment] 2020-10-05 17:16
Hi @northernSage , thanks for taking a look at this issue.

I created a minimal application here: https://github.com/cquick01/xprocess-test that can be used to test. I put the instructions to reproduce the bug in the `README.md` file.

I also noticed that when running `pytest tests/` the first time, it hangs. But, if I hit `ctrl-c` and retry the tests, it succeeds, since it appears that the server process is still running in the background afterwards. Unfortunately since this is being used in CI, that isn't always an option.

Hopefully this helps to track down the issue. Thank you again for looking into it, and let me know if there is anything else I can provide to help.

**Comment by northernSage** [comment] 2020-10-05 22:25
@cquick01 First of all thanks for the excellent documentation/explanation of the issue, it makes things a lot easier. Now, to what seems to be the solution to your problem:

```python
# ...
class Starter(ProcessStarter):
    pattern = "HostSim server running"
    # extra "-u" flag in order to skip buffering for the python process
    args = [python_executable_full_path, '-u', '-m', 'xprocess_test.host_sim']
# ...
```
The explanation for this is that, by default, Python buffers output to `stdout` (`stderr` too if memory doesn't fail me), consequently your start pattern `"HostSim server running"` wasn't actually being printed to the shell and `xprocess.ensure("host_sim", Starter)` was waiting (indefinetly) for your process to start (since it couldn't detect it). All I did was add the "-u" flag to your process execution command in order to disable buffering and it worked just fine on the provided docker container.

On a side note, the reason it would work after hitting `ctrl-c` was the non-termination of the server process since the statement `xprocess.getinfo("host_sim").terminate()` would never execute due to the interrupt. If you run pytest again, once the process was already running in the background from the previous attempt, `xprocess.ensure("host_sim", Starter)`  would just pass without trying to match the start pattern.

**Comment by cquick01** [comment] 2020-10-06 14:39
Hi @northernSage . This did seem to work in the Docker container itself, but unfortunately I am still running into issues when running in CI (GitLab).

It seems like the process doesn't correctly write to `stdout` when running in CI. I tried digging a little bit more into the `xprocess` code, but couldn't figure out a way to get it working. I assume it is more-so an issue with the GitLab Runner doing something behind the scene with `stdout`. Maybe at some point I'll get it working and can open a PR if needed.

Thanks for the help, it at least solved the issue on the Docker side of things. Feel free to close this issue, unless you're interested in testing with GitLab CI, in case others are quietly experiencing issues. 👍

**Comment by northernSage** [comment] 2020-10-07 01:38
Well, I'm glad we could help you reach at least a partial solution. I will be closing this for now since issues with Gitlab CI are a bit out of scope here (given pytest-flask seems to be running as it should in both containerized and local machines). Feel free to reopen if you find that the problem is related to pytest-flask or to just document your chosen solution for people who may face the same situation as you.

**Closed by northernSage** 2020-10-07 01:38 UTC
Labels: bug

**Comment by cquick01** [comment] 2020-10-07 15:50
I was actually able to get it working in GitLab CI this morning.

The trick for getting it to work, for me at least, was adding `--capture=tee-sys` to the `pytest` call. See:  https://docs.pytest.org/en/stable/capture.html

I also added `-u` to the python call to `host_sim` (as described above), as well as added to the python call to `pytest`.

```
PYTHONPATH=. python -u -m pytest --capture=tee-sys --cov my_package tests/
```

Now our CI pytest stage is completing successfully, with `xprocess` being used to launch our server simulator module.

Thanks again for the help, it got me moving in the right direction 😃

**Comment by northernSage** [comment] 2020-10-07 16:36
Hm, considering this issue and also #16 I think it might be worth documenting the potential hiccups related to stream buffering when starting external python processes with pytest-xprocess. Maybe a new section after [fixture-usage instructions](https://github.com/pytest-dev/pytest-xprocess#xprocess-fixture-usage)? WDYT @nicoddemus

**Comment by nicoddemus** [comment] 2020-10-07 17:00
> Maybe a new section after fixture-usage instructions? WDYT @nicoddemus

Definitely seems like something we should mention, as this is quite a common problem.
